# Generated by Django 2.2.8 on 2019-12-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_pk', models.IntegerField(db_index=True)),
                ('team_code', models.CharField(max_length=100)),
                ('club_id', models.IntegerField()),
                ('club', models.CharField(max_length=100)),
                ('club_common_name', models.CharField(max_length=100)),
                ('club_full_name', models.CharField(max_length=100)),
                ('name_display_long', models.CharField(max_length=100)),
                ('name_display_short', models.CharField(max_length=100)),
                ('display_code', models.CharField(max_length=100)),
                ('venue_id', models.IntegerField()),
                ('field', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=100)),
                ('aws_club_slug', models.CharField(max_length=100)),
                ('youtube', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first_last', models.CharField(max_length=50)),
                ('name_last_first', models.CharField(max_length=50)),
                ('player_first_last_html', models.CharField(max_length=50)),
                ('player_html', models.CharField(max_length=50)),
                ('jersey_number', models.CharField(max_length=50)),
                ('primary_position', models.CharField(max_length=50)),
                ('primary_position_cd', models.CharField(max_length=50)),
                ('position_desig', models.CharField(max_length=50)),
                ('throws', models.CharField(max_length=50)),
                ('bats', models.CharField(max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Team')),
            ],
        ),
    ]
