# Generated by Django 2.2.8 on 2019-12-14 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateTimeField()),
                ('game_league', models.CharField(max_length=100)),
                ('game_start_time', models.CharField(max_length=100)),
                ('game_status', models.CharField(max_length=100)),
                ('game_tag', models.CharField(max_length=100)),
                ('home_team_runs', models.IntegerField()),
                ('away_team_runs', models.IntegerField()),
                ('home_team_hits', models.IntegerField()),
                ('away_team_hits', models.IntegerField()),
                ('home_team_errors', models.IntegerField()),
                ('away_team_errors', models.IntegerField()),
                ('w_pitcher', models.CharField(max_length=100)),
                ('l_pitcher', models.CharField(max_length=100)),
                ('w_pitcher_wins', models.IntegerField()),
                ('l_pitcher_wins', models.IntegerField()),
                ('w_pitcher_losses', models.IntegerField()),
                ('l_pitcher_losses', models.IntegerField()),
                ('sv_pitcher', models.CharField(max_length=100)),
                ('sv_pitcher_saves', models.IntegerField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_team', to='game.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_team', to='game.Team')),
                ('l_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_team_team', to='game.Team')),
                ('w_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_team_team', to='game.Team')),
            ],
        ),
    ]
