# Generated by Django 2.2.8 on 2019-12-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_team_errors',
        ),
        migrations.RemoveField(
            model_name='game',
            name='away_team_hits',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_league',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_start_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_tag',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team_errors',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team_hits',
        ),
        migrations.RemoveField(
            model_name='game',
            name='l_pitcher_losses',
        ),
        migrations.RemoveField(
            model_name='game',
            name='l_pitcher_wins',
        ),
        migrations.RemoveField(
            model_name='game',
            name='sv_pitcher_saves',
        ),
        migrations.RemoveField(
            model_name='game',
            name='w_pitcher_losses',
        ),
        migrations.RemoveField(
            model_name='game',
            name='w_pitcher_wins',
        ),
    ]
