# Generated by Django 2.2.8 on 2019-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191214_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='l_pitcher',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='sv_pitcher',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='w_pitcher',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
