# Generated by Django 2.2.8 on 2019-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20191214_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sv_pitcher',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
