# Generated by Django 2.2.8 on 2019-12-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='youtube_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
