# Generated by Django 2.2.8 on 2019-12-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_youtube_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='original_audio_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='original_video_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
