# Generated by Django 2.2.8 on 2019-12-14 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_atbat_inning_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='at_bat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.AtBat'),
            preserve_default=False,
        ),
    ]
