# Generated by Django 2.2.8 on 2019-12-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_pitch_at_bat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='pitch_result',
            field=models.CharField(choices=[('B', 'ball'), ('S', 'strike'), ('X', 'in play')], max_length=500, verbose_name='pitch result'),
        ),
    ]
