# Generated by Django 2.2.8 on 2019-12-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20191214_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='youtube_start_offset',
            field=models.IntegerField(default=0),
        ),
    ]
