# Generated by Django 2.2.8 on 2019-12-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_game_youtube_start_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atbat',
            name='inning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='at_bat', to='game.Inning'),
        ),
    ]
