# Generated by Django 2.2.8 on 2019-12-14 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20191214_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atbat',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='inning',
            options={'ordering': ['inning', 'top_bottom__desc']},
        ),
        migrations.AlterModelOptions(
            name='pitch',
            options={'ordering': ['pitch_datetime']},
        ),
        migrations.AlterField(
            model_name='inning',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='game.Game'),
        ),
    ]
