# Generated by Django 2.2.8 on 2019-12-14 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20191214_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='at_bat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='game.AtBat'),
        ),
    ]
