# Generated by Django 2.2.8 on 2019-12-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20191214_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inning',
            options={'ordering': ['game__date', 'inning']},
        ),
    ]
